spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/unique_wear
        driver-class-name: org.postgresql.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        properties:
            hibernate:
                format_sql: true
                hbm2ddl:
                    auto: update
                dialect: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
    application:
        name: unique-wear
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true
jwt:
    auth:
        app: authApp
        secret_key: ${JWT_KEY}
        expires_id: 3600



logging:
    level:
        org:
            springframework:
                web: debug
                http:
                    converter:
                        json: debug
            modelmapper: debug
#server:
#  servlet:
#      context-path: /api

#    devtools:
#        livereload:
#            enabled: true
#        restart:
#            enabled: true
#            additional-paths:
#                - src/main/java
#            poll-interval: 500ms
#            quiet-period: 200ms
#            additional-exclude: static/**,templates/**